ignore:
  - "webapp/**"
  - "**/generated/**"
  - "**/migrations/**"

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 70%
        threshold: 10%
      - type: patch
        target: 75%
        threshold: 10%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
