"""Observability — typed event emit helpers for the 14-event scan-engine allowlist.

See `.claude/rules/telemetry.md` § Event allowlist for the full contract.
The typed helpers live here; the scan engine and the vendor / re-scan paths
emit the events.
"""

from app.observability.events import (
    BackoffSecondsBucket,
    BodyLengthBucket,
    CountBucket,
    FailureClass,
    FpRateBucket,
    GitHubRateLimitKind,
    GitHubResource,
    HashDeltaBucket,
    LatencyBucket,
    ScanSource,
    ScanStage,
    Severity,
    StatusAtScan,
    SubScore,
    TierBucket,
    count_bucket,
    emit_github_rate_limit_hit,
    emit_github_rate_limit_recovered,
    emit_rescan_triggered_drift,
    emit_rule_fired,
    emit_rule_shadow_demoted,
    emit_rule_shadow_promoted,
    emit_rule_skipped_timeout,
    emit_scan_completed,
    emit_scan_failed,
    emit_scan_started,
    emit_scan_submitted,
    emit_scan_timeout,
    emit_vendor_response_submitted,
    emit_vendor_verification_succeeded,
    hash_to_bucket,
    latency_bucket,
)

__all__ = [
    "BackoffSecondsBucket",
    "BodyLengthBucket",
    "CountBucket",
    "FailureClass",
    "FpRateBucket",
    "GitHubRateLimitKind",
    "GitHubResource",
    "HashDeltaBucket",
    "LatencyBucket",
    "ScanSource",
    "ScanStage",
    "Severity",
    "StatusAtScan",
    "SubScore",
    "TierBucket",
    "count_bucket",
    "emit_github_rate_limit_hit",
    "emit_github_rate_limit_recovered",
    "emit_rescan_triggered_drift",
    "emit_rule_fired",
    "emit_rule_shadow_demoted",
    "emit_rule_shadow_promoted",
    "emit_rule_skipped_timeout",
    "emit_scan_completed",
    "emit_scan_failed",
    "emit_scan_started",
    "emit_scan_submitted",
    "emit_scan_timeout",
    "emit_vendor_response_submitted",
    "emit_vendor_verification_succeeded",
    "hash_to_bucket",
    "latency_bucket",
]
