#!/usr/bin/env node
/**
 * generate-zod.cjs — Zod runtime validator emission from schemas/*.schema.json.
 *
 * Minimal emitter — writes a single index.ts under webapp/src/generated/zod/
 * containing one Zod schema per JSON Schema. A later rewrite will
 * either swap to `ts-to-zod` over the generated TS DTOs OR a direct
 * `json-schema-to-zod` pipeline, depending on which preserves descriptions
 * better.
 */
'use strict'

const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.resolve(__dirname, '..')
const SCHEMAS_DIR = path.join(ROOT, 'schemas')
const OUT_DIR = path.join(ROOT, 'webapp', 'src', 'generated', 'zod')

fs.mkdirSync(OUT_DIR, { recursive: true })

const schemas = fs.readdirSync(SCHEMAS_DIR).filter((f) => f.endsWith('.schema.json'))

let out = `// Generated by scripts/generate-zod.cjs — do not edit.\n`
out += `// Placeholder shape. Real Zod emission lands later.\n\n`
out += `import { z } from 'zod';\n\n`

for (const file of schemas) {
  const stem = file.replace(/\.schema\.json$/, '')
  const ConstName = stem
    .split('-')
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join('')
  out += `// ${file}\n`
  out += `export const ${ConstName}Schema = z.unknown();\n`
  out += `export type ${ConstName} = z.infer<typeof ${ConstName}Schema>;\n\n`
}

// Normalize trailing newlines: single \n at EOF (matches end-of-file-fixer).
fs.writeFileSync(path.join(OUT_DIR, 'index.ts'), out.replace(/\n+$/, '\n'))
console.log(`[zod] Wrote ${path.relative(ROOT, path.join(OUT_DIR, 'index.ts'))}.`)
