#!/usr/bin/env node
/**
 * generate-zod.cjs — Zod runtime validator emission from schemas/*.schema.json.
 *
 * W1 minimal emitter — writes a single index.ts under webapp/src/generated/zod/
 * containing one Zod schema per JSON Schema. The W2 rewrite (Track A/B) will
 * either swap to `ts-to-zod` over the generated TS DTOs OR a direct
 * `json-schema-to-zod` pipeline, depending on which preserves descriptions
 * better.
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const SCHEMAS_DIR = path.join(ROOT, 'schemas');
const OUT_DIR = path.join(ROOT, 'webapp', 'src', 'generated', 'zod');

fs.mkdirSync(OUT_DIR, { recursive: true });

const schemas = fs
  .readdirSync(SCHEMAS_DIR)
  .filter((f) => f.endsWith('.schema.json'));

let out = `// Generated by scripts/generate-zod.cjs — do not edit.\n`;
out += `// W1 placeholder shape. Real Zod emission lands W2 (Track A).\n\n`;
out += `import { z } from 'zod';\n\n`;

for (const file of schemas) {
  const stem = file.replace(/\.schema\.json$/, '');
  const ConstName = stem
    .split('-')
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join('');
  out += `// ${file}\n`;
  out += `export const ${ConstName}Schema = z.unknown();\n`;
  out += `export type ${ConstName} = z.infer<typeof ${ConstName}Schema>;\n\n`;
}

fs.writeFileSync(path.join(OUT_DIR, 'index.ts'), out);
console.log(`[zod] Wrote ${path.relative(ROOT, path.join(OUT_DIR, 'index.ts'))}.`);
