"""Async SQLAlchemy engine + session factory.

The scan engine + routers consume this via FastAPI dependency injection.

Primary keys across the scan surface are UUIDv4 generated by PostgreSQL's
native `gen_random_uuid()`. Models declare `server_default=text("gen_random_uuid()")`
rather than a Python factory — keeps inserts cheap, no extension or polyfill
needed. The time-orderable-ID intent is dropped for now; revisit if a
scan-listing query proves the ordering matters.
"""

from __future__ import annotations

from collections.abc import AsyncIterator

from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

from app.core.config import Settings, get_settings

_settings = get_settings()


def engine_connect_args(settings: Settings) -> dict[str, object]:
    """asyncpg `connect_args` that bound a slow query so a saturated DB fast-fails.

    `statement_timeout` (ms) makes Postgres ABORT any statement exceeding it
    (SQLSTATE 57014 → `app/main.py`'s handler maps it to a bounded 503), freeing
    the pooled connection instead of letting one slow query hang every request
    behind the pool-checkout timeout. `idle_in_transaction_session_timeout` (ms)
    reclaims a connection left idle inside an open transaction. Both are
    PER-STATEMENT / per-idle, so the chunked bulk-scan writes (each fast) are
    safe; alembic runs on a SEPARATE engine (`migrations/env.py`) and is
    unaffected. The two long-lived advisory-lock holders (the migration lock in
    `core/startup.py`, the procrastinate-schema lock in `ingestion/worker.py`)
    disable both via `SET LOCAL`, and the CONCURRENTLY materialized-view refresh
    (`ingestion/tasks_authors.py`) runs on a dedicated unbounded engine — none of
    them must be aborted mid-operation.

    `command_timeout` (s) is the asyncpg client-side backstop for a wholly
    unresponsive server; off by default (`db_command_timeout_s == 0`). Either
    knob set to 0 is omitted entirely.
    """
    server_settings: dict[str, str] = {}
    if settings.db_statement_timeout_s > 0:
        ms = str(settings.db_statement_timeout_s * 1000)
        server_settings["statement_timeout"] = ms
        server_settings["idle_in_transaction_session_timeout"] = ms
    args: dict[str, object] = {}
    if server_settings:
        args["server_settings"] = server_settings
    if settings.db_command_timeout_s > 0:
        args["command_timeout"] = settings.db_command_timeout_s
    return args


def _engine_kwargs(settings: Settings) -> dict[str, object]:
    """Pool + connect kwargs for the shared async engine.

    `pool_recycle` (when > 0) caps the age of any pooled connection so one
    silently dropped by a proxy / 6PN / PG-side close can't outlive the window —
    the PROACTIVE half of half-open-connection defence (asyncpg has no TCP
    keepalive knob). It pairs with `pool_pre_ping` (liveness check on checkout)
    and the connect-arg `command_timeout` (the REACTIVE bound that makes both the
    pre-ping AND a real query fail-fast on a dead socket instead of hanging
    forever — the staging incident where every DB request hung with no 503).
    """
    kwargs: dict[str, object] = {
        "echo": False,
        "pool_pre_ping": True,
        "pool_size": settings.db_pool_size,
        "max_overflow": settings.db_max_overflow,
        # Back-pressure: raise TimeoutError after this many seconds instead of
        # blocking forever when ingestion + API jointly exhaust the shared pool.
        "pool_timeout": settings.db_pool_timeout_s,
        # statement_timeout (server-side, → 503) bounds a slow QUERY;
        # command_timeout (client-side) bounds a DEAD CONNECTION. See
        # engine_connect_args.
        "connect_args": engine_connect_args(settings),
    }
    if settings.db_pool_recycle_s > 0:
        kwargs["pool_recycle"] = settings.db_pool_recycle_s
    return kwargs


async_engine = create_async_engine(_settings.database_url, **_engine_kwargs(_settings))

AsyncSessionLocal = async_sessionmaker(
    bind=async_engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


async def get_session() -> AsyncIterator[AsyncSession]:
    """FastAPI dependency: yields a per-request `AsyncSession`."""
    async with AsyncSessionLocal() as session:
        yield session
