"""Async SQLAlchemy engine + session factory.

W2 Phase A — Track A foundation. The scan engine + routers consume this via
FastAPI dependency injection in Phase B.

Primary keys across the scan surface are UUIDv7 generated by PostgreSQL 17's
native `gen_uuid_v7()` (locked decision D-28). Models declare
`server_default=text("gen_uuid_v7()")` rather than a Python factory — keeps
inserts cheap and time-ordered without an extra dep.
"""

from __future__ import annotations

from collections.abc import AsyncIterator

from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

from app.core.config import get_settings

_settings = get_settings()

async_engine = create_async_engine(
    _settings.database_url,
    echo=False,
    pool_pre_ping=True,
    pool_size=10,
    max_overflow=20,
)

AsyncSessionLocal = async_sessionmaker(
    bind=async_engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


async def get_session() -> AsyncIterator[AsyncSession]:
    """FastAPI dependency: yields a per-request `AsyncSession`."""
    async with AsyncSessionLocal() as session:
        yield session
