"""Async SQLAlchemy engine + session factory.

The scan engine + routers consume this via FastAPI dependency injection.

Primary keys across the scan surface are UUIDv4 generated by PostgreSQL's
native `gen_random_uuid()`. Models declare `server_default=text("gen_random_uuid()")`
rather than a Python factory — keeps inserts cheap, no extension or polyfill
needed. The time-orderable-ID intent is dropped for now; revisit if a
scan-listing query proves the ordering matters.
"""

from __future__ import annotations

from collections.abc import AsyncIterator

from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

from app.core.config import get_settings

_settings = get_settings()

async_engine = create_async_engine(
    _settings.database_url,
    echo=False,
    pool_pre_ping=True,
    pool_size=_settings.db_pool_size,
    max_overflow=_settings.db_max_overflow,
    # Back-pressure: raise TimeoutError after this many seconds instead of
    # blocking forever when ingestion + API jointly exhaust the shared pool.
    # A bounded, observable 503 beats a silent hang.
    pool_timeout=_settings.db_pool_timeout_s,
)

AsyncSessionLocal = async_sessionmaker(
    bind=async_engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


async def get_session() -> AsyncIterator[AsyncSession]:
    """FastAPI dependency: yields a per-request `AsyncSession`."""
    async with AsyncSessionLocal() as session:
        yield session
