import mdx from '@astrojs/mdx'
import starlight from '@astrojs/starlight'
import { defineConfig } from 'astro/config'

// SaferSkills Documentation — Starlight SSG build (I-06 Plan 1, D-2/D-3).
//
// This is the SECOND Astro config in the @saferskills/webapp package. The main
// site (astro.config.mjs) is SSR (`output: 'server'`); the docs are 100% static
// (`output: 'static'`) and served at `/docs/*`.
//
// Why a dedicated `srcDir`/`outDir` instead of the plan's literal
// `webapp/src/content/docs/`: a second Astro config in the same package still
// scans `{srcDir}/pages`. Pointing it at the main `./src` would drag the 30+
// SSR app pages into a static build and fail. Isolating the docs tree under
// `./docs` keeps the two builds from colliding while honoring D-2 (one package).
//
// `base: '/docs'` is what produces the `/docs/*` routes for a standalone
// Starlight build (the design's "no base directive" note was written for a
// single-config nested-collection world; it does not apply here). Internal
// markdown links still carry the manual `/docs/` prefix per D-6.
//
// Build output (`dist-docs/docs/**`) is copied into the main build's
// `dist/client/docs` by the `build:docs` script so the webapp's Node SSR server
// serves it as a static fall-through. See plan/01-scaffold.md § Build &
// Deployment Strategy.
export default defineConfig({
  site: 'https://saferskills.ai',
  base: '/docs',
  srcDir: './docs',
  outDir: './dist-docs',
  output: 'static',
  integrations: [
    starlight({
      title: 'SaferSkills Docs',
      description:
        'Learn SaferSkills. Find and verify AI capabilities, install with confidence, read the methodology behind every scan, and run an Agent Scan.',
      tagline: 'Every AI capability, independently scanned.',
      favicon: '/favicon.svg',
      // Brand theming via CSS custom properties only (cascade layers) — teal
      // #0D9488 + DM Sans / Space Mono, 0px radius, no shadows. No component
      // forks. See docs/styles/saferskills-docs.css.
      customCss: ['./docs/styles/saferskills-docs.css'],
      // Open-contribution: edit-on-GitHub links resolve to the monorepo content
      // file. Starlight appends the page's source path relative to the Astro
      // project root (webapp/) — i.e. `docs/content/docs/<slug>.md` — so the base
      // must stop at `webapp/`. Going deeper double-counts the collection path.
      editLink: {
        baseUrl: 'https://github.com/OpenLatch/saferskills/edit/main/webapp/',
      },
      // Pagefind static search (Starlight built-in). Explicitly enabled per the
      // Plan 1 risk note (do not rely on zero-config in 0.40).
      pagefind: true,
      // Single-source agent + theme sync: carry the main site's stored theme
      // (`localStorage['ss-theme']`) into the docs before first paint so the
      // toggle state is consistent site-wide (D-5). Runs ahead of Starlight's
      // own theme script; also seeds `starlight-theme` so the built-in
      // ThemeSelect reflects the inherited choice.
      head: [
        // E-E-A-T authorship signal (Plan 3 SEO-D3). Authorship is uniformly the
        // "SaferSkills Team" (see the `author` frontmatter on analytical pages), so
        // a single global meta tag is accurate for every page — no per-page render
        // fork. The about page (/docs/reference/about/) is the team bio surface.
        { tag: 'meta', attrs: { name: 'author', content: 'SaferSkills Team' } },
        {
          tag: 'script',
          content: [
            '(function(){try{',
            "var m=localStorage.getItem('ss-theme')||'auto';",
            "var dark=m==='dark'||(m==='auto'&&matchMedia('(prefers-color-scheme: dark)').matches);",
            "var t=dark?'dark':'light';",
            'document.documentElement.dataset.theme=t;',
            "document.documentElement.classList.toggle('dark',dark);",
            "localStorage.setItem('starlight-theme',t);",
            '}catch(e){}})();',
          ].join(''),
        },
      ],
      // Autogenerated sidebar — one group per IA section. New `.md`/`.mdx`
      // under a directory joins its group automatically (open-contribution).
      sidebar: [
        { label: 'Getting Started', items: [{ autogenerate: { directory: 'getting-started' } }] },
        { label: 'Concepts', items: [{ autogenerate: { directory: 'concepts' } }] },
        { label: 'Find & Verify', items: [{ autogenerate: { directory: 'find-and-verify' } }] },
        { label: 'Agent Scan', items: [{ autogenerate: { directory: 'agent-scan' } }] },
        { label: 'Install (CLI)', items: [{ autogenerate: { directory: 'install' } }] },
        { label: 'For Authors', items: [{ autogenerate: { directory: 'for-authors' } }] },
        {
          label: 'Security & Methodology',
          items: [{ autogenerate: { directory: 'security-and-methodology' } }],
        },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
      ],
      // Footer attribution only — never cross-recommend OpenLatch (brand
      // independence). The "An OpenLatch project" line lives in the page footer.
      credits: false,
    }),
    mdx(),
  ],
})
