"""Generate Pydantic v2 models from JSON Schema files (datamodel-code-generator).

Ported from openlatch-platform's `generate_pydantic_models.py` and adapted for
SaferSkills:

* **Single-repo** — the upstream client-schemas materialization branch
  (`openlatch-client-schemas` PyPI package / `LOCAL_SCHEMAS_PATH`) is removed;
  SaferSkills reads `schemas/` directly.
* **Per-file invocation** (one schema → `app/schemas/generated/<stem>.py`) so module
  names stay stable (`catalog_item.py`, not the whole-dir `catalog_item_schema.py`)
  and every existing import keeps working.
* `--base-class app.schemas.orm_base.OrmBaseModel` so generated response models
  serialize snake_case keys (naming-conventions.md § API JSON Body Keys; makes
  schema-driven-development.md Hard rule #3 true).

Run via the `scripts/generate-pydantic.cjs` wrapper (part of `pnpm run generate`),
or directly: `uv run python scripts/generate_pydantic_models.py`.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SERVICE_ROOT = SCRIPT_DIR.parent  # services/api/
REPO_ROOT = SERVICE_ROOT.parent.parent  # repo root
SCHEMAS_DIR = REPO_ROOT / "schemas"
OUTPUT_DIR = SERVICE_ROOT / "app" / "schemas" / "generated"


def main() -> int:
    print("=== Generating Pydantic models ===")
    if not SCHEMAS_DIR.is_dir():
        print(f"Error: schemas directory not found at {SCHEMAS_DIR}", file=sys.stderr)
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    schema_files = sorted(SCHEMAS_DIR.glob("*.schema.json"))
    if not schema_files:
        print("Error: no *.schema.json files found", file=sys.stderr)
        return 1

    for path in schema_files:
        stem = path.name.replace(".schema.json", "").replace("-", "_")
        out_path = OUTPUT_DIR / f"{stem}.py"
        cmd = [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(path),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(out_path),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--base-class",
            "app.schemas.orm_base.OrmBaseModel",
            "--snake-case-field",
            "--use-double-quotes",
            "--use-schema-description",
            "--target-python-version",
            "3.12",
            "--use-standard-collections",
            "--use-union-operator",
            "--disable-timestamp",
        ]
        print(f"  {path.name} -> app/schemas/generated/{stem}.py")
        result = subprocess.run(cmd, cwd=str(SERVICE_ROOT))
        if result.returncode != 0:
            return result.returncode

    init_path = OUTPUT_DIR / "__init__.py"
    if not init_path.exists():
        init_path.write_text(
            "# Generated by scripts/generate_pydantic_models.py — do not edit.\n",
            encoding="utf-8",
        )

    print("[pydantic] OK.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
